### ISSUE TITLE
New file identifiers and FileTypeInfo class, extension groups and such

### ISSUE THREAD

**Issue by PredatorCZ** [gibbed/Gibbed.JustCause4#1]
Files with TAG0 signature are Havok 2016 tagfiles.
Files with KB2 magic are .bikc (Bink) files.
Files with RIFF magic are .fsb (Fmod 5) files.
New extension groups: 
{
*.modelc
*.meshc
*.hrmeshc
*_col.pfxc
}
Thank you for your tool btw.

**Comment by gibbed** [comment]
For Havok tagfiles, is the extension "tagfile" or is there a natural extension? Because JC4 uses multiple extensions for those.

**Comment by PredatorCZ** [comment]
I'm sorry I cannot tell you whinch extensions are used (Apex games are using a lot of them), but Havok uses .hkt for tagfiles in general.

**Comment by PredatorCZ** [comment]
Here's a complete dump of SARC filesystem, so you can commit it to project. This will add 3% of files (mostly textures)
[sarcFilesystemDump.zip](https://github.com/gibbed/Gibbed.JustCause4/files/2661076/sarcFilesystemDump.zip)

**Comment by gibbed** [comment]
Thanks.
