### ISSUE TITLE
Usage.

### ISSUE THREAD

**Issue by Underdisc** [gibbed/Gibbed.JustCause4#2]
I saw Gibbed.JustCause4.Unpack.exe and got a sample .arc and .tab pair from the game's files.

I used `Gibbed.JustCause4.Unpack.exe -o -nu -v game0.tab` and got a directory named game0_unpack/ as output within the working directory. I was wondering why -o didn't seem to overwrite anything. I also don't fully understand what -nu is for.

After I make my modifications to game0_unpack, what do I do with it to run the game with those modifications?

Additionally, I was looking around in game0_unpack/ to see what your executable pooped out from game0.arc and game0.tab. All I saw was data for ai navigation meshes. I am just looking to change some constants, but I need to find them. I noticed a lot of files named game*.filelist in projects/Just Cause 4/files/archives_win64/.  After looking at the them, I realized it described what is contained inside of every game*.tab and game*.arc file. Do you have any recommendations on the fastest way to browse through this tree of files before I waste my time unpacking them? Alternatively, do you have a way to unpack everything within archive_win64/ recursively or should I just make a script to do that for me?

**Unrelated to issue**
As I play the game, I keep thinking, man, it would be really nice if things just fell faster. I blew up a helicopter carrying one of those giant fuel balls and watched the ball very slowly fall to the ground. It got to the ground and the ball didn't even explode, and I assume that has to do with the speed it was moving. On top of that, I can glide over flat surfaces for way too long with the wing suit.

**Comment by gibbed** [comment]
`-o` is to overwrite files when they already exist in the target location, it doesn't mean anything if you're extracting to a fresh location.
`-nu` stops unpacking of unknown files (ie, files whos names are unknown).

To get the game to use your modified files, that's the point of `LaunchWithDropzone`, though I don't know its current state if it's still working on the most recent version of the game.

I don't have any suggestions for batch unpacking, generally I search through the file lists for what I'm after to know what archive I should be unpacking.
